application: searchchristapp
version: 1
runtime: python
api_version: 1

handlers:
- url: /tpl/.*
  script: app.py
  secure: optional

- url: /
  static_files: assets/index.html
  upload: assets/index.html
  
  
- url: /
  static_dir: assets
